##  **Data Preparation and Preprocessing for Tourism Analysis in Ireland**

#### **Importing Necessary Libraries**

We will import the required Python libraries for data manipulation, visualization, and numerical operations.

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#### **Loading a CSV File into a Pandas DataFrame**

To work with tabular data in Python, we use the **Pandas** library to read CSV (Comma-Separated Values) files. The following code loads a dataset into a Pandas DataFrame.

In [5]:
core_data=pd.read_csv(r"H:\CCT\Git\msc-da-ca1-sem-1-Nandini162003\Dataset\TMQ20.csv")

#### **Viewing the First Few Rows of a DataFrame**

After loading a dataset into a Pandas DataFrame, it's essential to inspect the first few rows to understand its structure. The **`head()`** method in Pandas helps achieve this.

In [7]:
core_data.head()

,Area of Residence,Reason for Journey,Quarter,Statistic Label,UNIT,VALUE
0,All Countries,All reasons for journey,2012Q1,Average Length of Stay by Overseas Travellers ...,Nights,6.8
1,All Countries,All reasons for journey,2012Q1,Expenditure by Overseas Travellers in Ireland ...,Euro Million,483.0
2,All Countries,All reasons for journey,2012Q1,"Overseas Trips to Ireland by Non-Residents, wi...",%,100.0
3,All Countries,All reasons for journey,2012Q2,Average Length of Stay by Overseas Travellers ...,Nights,7.0
4,All Countries,All reasons for journey,2012Q2,Expenditure by Overseas Travellers in Ireland ...,Euro Million,816.0

#### **Getting Information About the DataFrame Structure**

The **`info()`** method in Pandas provides a quick summary of the DataFrame, giving you an overview of its structure, data types, memory usage, and null value counts. It is especially useful for quickly checking the integrity and completeness of the data before performing any analysis.

In [9]:
core_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3840 entries, 0 to 3839
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Area of Residence   3840 non-null   object
 1   Reason for Journey  3840 non-null   object
 2   Quarter             3840 non-null   object
 3   Statistic Label     3840 non-null   object
 4   UNIT                3840 non-null   object
 5   VALUE               3840 non-null   float64
dtypes: float64(1), object(5)
memory usage: 180.1+ KB

#### **Statistical Summary of a DataFrame**

The **`describe()`** method in Pandas provides a statistical summary of the numerical columns in a DataFrame. This is useful for quickly understanding the distribution and key statistics of the dataset.

In [11]:
core_data.describe()

             VALUE
count  3840.000000
mean     46.485911
std     128.569965
min       0.500000
25%       6.400000
50%      10.500000
75%      33.725000
max    1832.000000

#### **Dropping `UNIT` Column from a DataFrame**

In data preprocessing, we need to remove unnecessary columns. The **`drop()`** method in Pandas allows us to delete specific columns from a DataFrame.

In [13]:
core_data = core_data.drop(columns=['UNIT'], axis=1)

#### Pivoting a DataFrame in Pandas

Pivoting is a powerful data transformation technique that reshapes a DataFrame from a long format to a wide format. The **`pivot()`** method in Pandas allows us to reorganize data by specifying **index**, **columns**, and **values**.

In [15]:
core_data_pivoted = core_data.pivot(index=['Area of Residence', 'Reason for Journey', 'Quarter'], 
                                          columns='Statistic Label', 
                                          values='VALUE').reset_index()

#### Viewing the First Few Rows of the Pivoted DataFrame

After pivoting a DataFrame using **`pivot()`**, it’s important to inspect the transformed data. The **`head()`** method in Pandas allows us to quickly view the first few rows.

In [17]:
core_data_pivoted.head()

Statistic Label,Area of Residence,Reason for Journey,Quarter,Average Length of Stay by Overseas Travellers to Ireland,Expenditure by Overseas Travellers in Ireland (excluding fares),"Overseas Trips to Ireland by Non-Residents, with at least one overnight in Ireland"
0,All Countries,All reasons for journey,2012Q1,6.8,483.0,100.0
1,All Countries,All reasons for journey,2012Q2,7.0,816.0,100.0
2,All Countries,All reasons for journey,2012Q3,8.1,994.0,100.0
3,All Countries,All reasons for journey,2012Q4,7.2,622.0,100.0
4,All Countries,All reasons for journey,2013Q1,6.7,541.0,100.0

#### Renaming Columns in a Pandas DataFrame

When working with datasets, column names may be too long or unclear. The **`rename()`** method in Pandas allows us to rename columns for better readability and usability.

In [19]:
core_data_pivoted.rename(columns={"Average Length of Stay by Overseas Travellers to Ireland": "Visitor Stay Avg",
                               "Expenditure by Overseas Travellers in Ireland (excluding fares)": "Visitor Spending",
                               "Overseas Trips to Ireland by Non-Residents, with at least one overnight in Ireland":"Overnight Tourist Trips"}, inplace=True)

#### Removing the Name of the Column Index in a Pandas DataFrame

When a DataFrame is **pivoted**, the new column headers may have a name assigned to them (e.g., `'Statistic Label'`). The **`columns.name = None`** method removes this name, ensuring a cleaner dataset.

In [21]:
core_data_pivoted.columns.name = None

#### **Extracting Year and Quarter from a Column in Pandas**

When working with time-based data, it’s common to extract specific components like **Year** and **Quarter** from a combined column. The `.str` accessor in Pandas helps perform string operations on DataFrame columns.

In [23]:
core_data_pivoted['Year'] = core_data_pivoted['Quarter'].str[:4]
core_data_pivoted['Quarter'] = core_data_pivoted['Quarter'].str[-1]

#### **Viewing the First Few Rows of the Pivoted DataFrame**

After transforming and cleaning the DataFrame, it's essential to check if the modifications were applied correctly. The **`head()`** method in Pandas helps display the first few rows of a DataFrame.

In [25]:
core_data_pivoted.head()

,Area of Residence,Reason for Journey,Quarter,Visitor Stay Avg,Visitor Spending,Overnight Tourist Trips,Year
0,All Countries,All reasons for journey,1,6.8,483.0,100.0,2012
1,All Countries,All reasons for journey,2,7.0,816.0,100.0,2012
2,All Countries,All reasons for journey,3,8.1,994.0,100.0,2012
3,All Countries,All reasons for journey,4,7.2,622.0,100.0,2012
4,All Countries,All reasons for journey,1,6.7,541.0,100.0,2013

#### **Reindexing Columns in a Pandas DataFrame**

Reindexing allows you to rearrange the columns in a DataFrame in a specific order. The **`reindex()`** method is used to reorder or change the columns to a new list.

In [27]:
reindex = ['Year', 'Quarter', 'Area of Residence', 'Reason for Journey', 'Visitor Stay Avg','Visitor Spending','Overnight Tourist Trips']

core_data_pivoted = core_data_pivoted.reindex(columns= reindex)

#### **Converting Column Data Types in Pandas**

In Pandas, it's common to convert the data type of a column to ensure consistency and make the data more suitable for analysis. The **`astype()`** method is used for type conversion.

In [29]:
core_data_pivoted["Year"] = core_data_pivoted["Year"].astype(int)
core_data_pivoted["Quarter"] = core_data_pivoted["Quarter"].astype(int)

#### **Viewing the First Few Rows of the Pivoted DataFrame**

After performing data transformations such as reindexing, renaming columns, or type conversion, it's important to **inspect the first few rows** to ensure that the changes were applied correctly. The **`head()`** method in Pandas provides a simple way to view the first few rows of a DataFrame.

In [31]:
core_data_pivoted.head()

,Year,Quarter,Area of Residence,Reason for Journey,Visitor Stay Avg,Visitor Spending,Overnight Tourist Trips
0,2012,1,All Countries,All reasons for journey,6.8,483.0,100.0
1,2012,2,All Countries,All reasons for journey,7.0,816.0,100.0
2,2012,3,All Countries,All reasons for journey,8.1,994.0,100.0
3,2012,4,All Countries,All reasons for journey,7.2,622.0,100.0
4,2013,1,All Countries,All reasons for journey,6.7,541.0,100.0

#### **Generating Descriptive Statistics for the Pivoted DataFrame**

After transforming and cleaning the data, it's important to gain insights into its distribution, central tendency, and spread. The **`describe()`** method in Pandas provides summary statistics for numerical columns in a DataFrame.

In [33]:
core_data_pivoted.describe()

,Year,Quarter,Visitor Stay Avg,Visitor Spending,Overnight Tourist Trips
count,1280.000000,1280.000000,1280.000000,1280.000000,1280.000000
mean,2015.500000,2.500000,9.336641,105.121875,24.999219
std,2.292183,1.118471,6.216477,208.178900,30.909652
min,2012.000000,1.000000,0.500000,1.000000,1.000000
25%,2013.750000,1.750000,5.900000,12.000000,6.000000
50%,2015.500000,2.500000,7.700000,37.000000,11.000000
75%,2017.250000,3.250000,10.225000,106.250000,27.000000
max,2019.000000,4.000000,49.400000,1832.000000,100.000000

#### **Getting Information About the DataFrame Structure**

To understand the basic structure of a DataFrame, the **`info()`** method in Pandas provides a concise summary. This method is useful for understanding the **data types**, **memory usage**, and **null value counts** of each column.

In [35]:
core_data_pivoted.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1280 entries, 0 to 1279
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Year                     1280 non-null   int32
 1   Quarter                  1280 non-null   int32
 2   Area of Residence        1280 non-null   object
 3   Reason for Journey       1280 non-null   object
 4   Visitor Stay Avg         1280 non-null   float64
 5   Visitor Spending         1280 non-null   float64
 6   Overnight Tourist Trips  1280 non-null   float64
dtypes: float64(3), int32(2), object(2)
memory usage: 60.1+ KB

In [36]:
core_data_wo_agg = core_data_pivoted[(core_data_pivoted['Reason for Journey'] != 'All reasons for journey') & (core_data_pivoted['Area of Residence'] != 'All Countries')].reset_index(drop=True)

In [37]:
core_data_wo_agg.head()

,Year,Quarter,Area of Residence,Reason for Journey,Visitor Stay Avg,Visitor Spending,Overnight Tourist Trips
0,2012,1,France,Business,6.6,9.0,9.0
1,2012,2,France,Business,5.8,6.0,6.0
2,2012,3,France,Business,9.3,6.0,7.0
3,2012,4,France,Business,9.1,5.0,5.0
4,2013,1,France,Business,6.0,7.0,8.0

In [38]:
#core_data_wo_agg.to_excel(r"H:\CCT\Git\msc-da-ca1-sem-1-Nandini162003\Dataset\Processed Data.xlsx", index=False)